service: geogame
image: j0ni1/geogame

servers:
  web:
    hosts:
      - 46.224.93.124

proxy:
  ssl: true
  host: geo.iguanodon.space
  response_timeout: 30

registry:
  username: j0ni1
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - geogame_storage:/rails/storage

asset_path: /rails/public/assets

builder:
  arch: amd64
